resolver: lts-12.9

packages:
  - '.'

extra-deps:
  - kansas-lava-0.2.4.5
  - sized-types-0.3.5.2

  - data-reify-0.6
  - dotgen-0.4.2
  - netlist-0.3.1
  - netlist-to-vhdl-0.3.3

flags:
  kansas-lava-cores:
    all: true
    unit: false
    spartan3e: false

extra-package-dbs: []
