boot::
	echo main | ghci -i../.. -i../../../kansas-lava Main.hs  -fcontext-stack=100

copy::


	scp main.vhd andygill@rome:xilinx/test3/main.vhd
	scp ../../../kansas-lava/Prelude/VHDL/Lava.vhd andygill@rome:xilinx/test3/Lava.vhd
